sudo: false
node_js: stable
language: node_js
addons:
  chrome: stable
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
  - yarn bootstrap
